[package]
name = "aurora_prompt"
version = "0.1.0"
authors = ["Odin Dutton <odindutton@gmail.com>"]
edition = "2018"

[dependencies]
nom = "5.1.1"
dirs = "2.0.2"
git2 = "0.13.5"
crossterm = "0.17.4"
clap = { git = "https://github.com/clap-rs/clap" }
anyhow = "1.0.28"
once_cell = "1.3.1"
